/*******************************************************************************
 * In the Hi-WAY project we propose a novel approach of executing scientific
 * workflows processing Big Data, as found in NGS applications, on distributed
 * computational infrastructures. The Hi-WAY software stack comprises the func-
 * tional workflow language Cuneiform as well as the Hi-WAY ApplicationMaster
 * for Apache Hadoop 2.x (YARN).
 *
 * List of Contributors:
 *
 * Hannes Schuh (HU Berlin)
 * Marc Bux (HU Berlin)
 * Jörgen Brandt (HU Berlin)
 * Ulf Leser (HU Berlin)
 *
 * Jörgen Brandt is funded by the European Commission through the BiobankCloud
 * project. Marc Bux is funded by the Deutsche Forschungsgemeinschaft through
 * research training group SOAMED (GRK 1651).
 *
 * Copyright 2014 Humboldt-Universität zu Berlin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package de.huberlin.hiwaydb.dal;

// Generated 19.05.2014 12:56:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Workflowrun generated by hbm2java
 */
@Entity
public class Workflowrun {

	@Id
	@GeneratedValue
	private Long id;
	private String runid;
	private String wfname;
	private Long wftime;
	@OneToMany(mappedBy = "workflowrun")
	private Set<Hiwayevent> hiwayevents = new HashSet<>(0);
	@OneToMany(mappedBy = "workflowrun")
	private Set<Invocation> invocations = new HashSet<>(0);

	public Workflowrun() {
	}

	public Workflowrun(String runid) {
		this.runid = runid;
	}

	public Workflowrun(String runid, String wfname, Long wftime, Set<Hiwayevent> hiwayevents, Set<Invocation> invocations) {
		this.runid = runid;
		this.wfname = wfname;
		this.wftime = wftime;
		this.hiwayevents = hiwayevents;
		this.invocations = invocations;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRunId() {
		return this.runid;
	}

	public void setRunId(String runid) {
		this.runid = runid;
	}

	public String getWfName() {
		return this.wfname;
	}

	public void setWfName(String wfname) {
		this.wfname = wfname;
	}

	public Long getWfTime() {
		return this.wftime;
	}

	public void setWfTime(Long wftime) {
		this.wftime = wftime;
	}

	public Set<Hiwayevent> getHiwayevents() {
		return this.hiwayevents;
	}

	public void setHiwayevents(Set<Hiwayevent> hiwayevents) {
		this.hiwayevents = hiwayevents;
	}

	public Set<Invocation> getInvocations() {
		return this.invocations;
	}

	public void setInvocations(Set<Invocation> invocations) {
		this.invocations = invocations;
	}

}
